#!/usr/bin/env python3
"""Regenerate the README model-capacity block from the global config."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Iterable

from aircraft_diffusion_cfd import (
    ConsistencyModel,
    DiffusionConfig,
    LatentDiffusionUNet,
    LatentTo3DConverter,
    ModelConfig,
    infer_conditioning_dim,
)
from experiment_config import GLOBAL_CONFIG, GLOBAL_CONFIG_PATH


START_MARKER = "<!-- MODEL_CAPACITY_START -->"
END_MARKER = "<!-- MODEL_CAPACITY_END -->"


def _parameter_count(parameters: Iterable) -> int:
    return sum(int(parameter.numel()) for parameter in parameters)


def _mib(byte_count: int) -> str:
    return f"{byte_count / (1024 ** 2):,.1f} MiB"


def _config_digest(config: dict) -> str:
    canonical = json.dumps(config, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]


def build_report() -> str:
    model_values = GLOBAL_CONFIG["model"]
    scaling_values = GLOBAL_CONFIG["scaling"]
    training_values = GLOBAL_CONFIG["training"]
    report_values = GLOBAL_CONFIG["report"]

    unique_count = int(scaling_values["capacity_basis_unique_geometries"])
    grid_resolution = int(model_values["grid_resolution"])
    latent_dim = int(model_values["latent_dim"])
    bytes_per_parameter = int(report_values["bytes_per_parameter"])

    model_config = ModelConfig.scaled_for_corpus(
        unique_count,
        grid_resolution,
        conditioning_dim=infer_conditioning_dim(),
        latent_dim=latent_dim,
    )
    diffusion_config = DiffusionConfig(teacher_steps=1000, student_steps=4)
    diffusion = LatentDiffusionUNet(model_config, diffusion_config)
    consistency = ConsistencyModel(model_config, diffusion_config)
    converter = LatentTo3DConverter(
        model_config.latent_dim,
        model_config.grid_resolution,
        coordinate_decoder_threshold=int(model_values["coordinate_decoder_threshold"]),
        coordinate_chunk_size=model_config.coordinate_chunk_size,
        coordinate_decoder_width=model_config.coordinate_decoder_width,
        coordinate_decoder_depth=model_config.coordinate_decoder_depth,
        coordinate_fourier_bands=model_config.coordinate_fourier_bands,
        enable_coordinate_gradient_checkpointing=bool(model_values["coordinate_gradient_checkpointing"]),
    )

    diffusion_count = _parameter_count(diffusion.parameters())
    student_count = _parameter_count(consistency.student_model.parameters())
    teacher_count = _parameter_count(consistency.teacher_model.parameters())
    converter_count = _parameter_count(converter.parameters())
    trainable_count = diffusion_count + student_count + converter_count

    # The trainer keeps a primary diffusion model, its EMA copy, a consistency
    # teacher and student, and the converter resident at once.
    resident_count = (2 * diffusion_count) + teacher_count + student_count + converter_count
    resident_weight_bytes = resident_count * bytes_per_parameter
    trainable_weight_bytes = trainable_count * bytes_per_parameter
    gradient_bytes = trainable_weight_bytes if bool(report_values["include_gradient_storage"]) else 0
    optimizer_bytes = (
        trainable_weight_bytes * int(report_values["optimizer_state_tensors_per_parameter"])
    )
    static_training_lower_bound = resident_weight_bytes + gradient_bytes + optimizer_bytes

    voxel_count = grid_resolution ** 3
    dense_grid_bytes = voxel_count * bytes_per_parameter
    coordinate_grid_bytes = voxel_count * 3 * bytes_per_parameter
    d3q27_population_bytes = voxel_count * 27 * bytes_per_parameter
    config_digest = _config_digest(GLOBAL_CONFIG)

    return "\n".join(
        [
            START_MARKER,
            "### Configured Model Capacity",
            "",
            "Generated by `python CLI/update_model_capacity_report.py` from "
            "[`CLI/config.yaml`](CLI/config.yaml).",
            "",
            f"- Config digest: `{config_digest}`",
            f"- Capacity basis: `{unique_count:,}` configured unique geometries (planning input, not a packaged-corpus claim)",
            f"- Lattice / latent width: `{grid_resolution}^3` / `{model_config.latent_dim}`",
            f"- Learning rates (diffusion / converter / consistency student): "
            f"`{training_values['learning_rate']}` / `{training_values['converter_learning_rate']}` / "
            f"`{training_values['consistency_student_learning_rate']}`",
            f"- Scaled channels: `{model_config.encoder_channels}`; coordinate decoder: "
            f"`{model_config.coordinate_decoder_width}` wide x `{model_config.coordinate_decoder_depth}` residual blocks",
            f"- Trainable parameters: `{trainable_count:,}` "
            f"(diffusion `{diffusion_count:,}`, consistency student `{student_count:,}`, converter `{converter_count:,}`)",
            f"- Trainable FP32 weight storage: `{_mib(trainable_weight_bytes)}`",
            f"- Resident training-model FP32 parameter storage, including teacher and EMA: `{_mib(resident_weight_bytes)}`",
            f"- Static FP32 training-memory lower bound with gradients and "
            f"{report_values['optimizer']} states: `{_mib(static_training_lower_bound)}`",
            f"- One dense scalar grid / coordinate grid / one D3Q27 population field: "
            f"`{_mib(dense_grid_bytes)}` / `{_mib(coordinate_grid_bytes)}` / `{_mib(d3q27_population_bytes)}`",
            "",
            "The memory values are deterministic storage calculations, not measured peak VRAM. "
            "Activations, allocator overhead, solver scratch arrays, and runtime libraries increase peak usage; "
            "measured runs remain the authority for hardware sizing.",
            END_MARKER,
        ]
    )


def update_readme(*, check: bool = False) -> bool:
    readme_path = (GLOBAL_CONFIG_PATH.parent / GLOBAL_CONFIG["report"]["readme_path"]).resolve()
    current = readme_path.read_text(encoding="utf-8")
    start = current.find(START_MARKER)
    end = current.find(END_MARKER)
    if start < 0 or end < start:
        raise ValueError(f"README is missing {START_MARKER} / {END_MARKER}")
    end += len(END_MARKER)
    updated = current[:start] + build_report() + current[end:]
    changed = updated != current
    if check and changed:
        raise SystemExit("README model-capacity report is stale; run CLI/update_model_capacity_report.py")
    if changed and not check:
        readme_path.write_text(updated, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when the checked-in README block is stale.")
    args = parser.parse_args()
    update_readme(check=args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
